// packages/scheduler-react/src/TlGrid.tsx
import React from 'react';

interface TlGridProps {
  startHour: number;
  endHour: number;
}

export function TlGrid({ startHour, endHour }: TlGridProps) {
  const hourCount = endHour - startHour;
  if (hourCount <= 0) return null;
  const hours: number[] = [];
  for (let h = startHour; h < endHour; h++) hours.push(h);

  return (
    <div
      className="tl-grid-header"
      style={{ '--tl-hour-count': hourCount } as React.CSSProperties}
    >
      {hours.map(h => {
        const left = ((h - startHour) / hourCount) * 100;
        return (
          <div key={h} className="tl-hour-label" style={{ left: `${left}%` }}>
            {String(h).padStart(2, '0')}:00
          </div>
        );
      })}
    </div>
  );
}

// packages/scheduler-vue/src/TlGrid.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ startHour: number; endHour: number }>();

const hourCount = computed(() => props.endHour - props.startHour);
const hours = computed(() => {
  const result: number[] = [];
  for (let h = props.startHour; h < props.endHour; h++) result.push(h);
  return result;
});
</script>

<template>
  <div v-if="hourCount > 0" class="tl-grid-header" :style="{ '--tl-hour-count': hourCount }">
    <div
      v-for="h in hours"
      :key="h"
      class="tl-hour-label"
      :style="{ left: `${((h - startHour) / hourCount) * 100}%` }"
    >
      {{ String(h).padStart(2, '0') }}:00
    </div>
  </div>
</template>
