// packages/scheduler-react/src/TlItem.tsx
import React, { useRef, useCallback, useState, useEffect } from 'react';
import type { TimelineItem } from '@breeze/core';

// Internal callback shapes — only used by TimelineScheduler
export interface TlItemDragStartDetail {
  item: TimelineItem;
  pointerId: number;
  clientX: number;
  itemClientLeft: number;
  itemClientWidth: number;
}

export interface TlItemResizeStartDetail {
  item: TimelineItem;
  edge: 'left' | 'right';
  pointerId: number;
  clientX: number;
  itemClientLeft: number;
  itemClientWidth: number;
}

interface TlItemProps {
  item: TimelineItem;
  dragEnabled: boolean;
  resizable: boolean;
  showTime: boolean;
  showTooltip: boolean;
  readonly: boolean;
  isDragging: boolean;
  renderContent?: ((item: TimelineItem) => React.ReactNode) | null;
  onDragStart: (detail: TlItemDragStartDetail) => void;
  onResizeStart: (detail: TlItemResizeStartDetail) => void;
  onClick: (item: TimelineItem) => void;
  onDblClick: (item: TimelineItem) => void;
  onHover: (item: TimelineItem, type: 'enter' | 'leave') => void;
  onContextMenu: (item: TimelineItem, x: number, y: number) => void;
  onKeyMove: (item: TimelineItem, direction: 'left' | 'right') => void;
}

function formatDuration(item: TimelineItem): string {
  const ms = item.end.getTime() - item.start.getTime();
  const totalMinutes = Math.round(ms / 60_000);
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

export function TlItem({
  item, dragEnabled, resizable, showTime, showTooltip,
  readonly, isDragging, renderContent,
  onDragStart, onResizeStart, onClick, onDblClick, onHover, onContextMenu, onKeyMove,
}: TlItemProps) {
  const blockRef = useRef<HTMLDivElement>(null);
  const downRef = useRef({ x: 0, y: 0, pointerId: -1, lastClickTime: 0 });
  const holdTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [tooltipVisible, setTooltipVisible] = useState(false);
  const [tooltipRect, setTooltipRect] = useState<DOMRect | null>(null);

  useEffect(() => {
    if (isDragging) {
      setTooltipVisible(false);
      setTooltipRect(null);
    }
  }, [isDragging]);

  const cleanHold = useCallback(() => {
    if (holdTimerRef.current !== null) {
      clearTimeout(holdTimerRef.current);
      holdTimerRef.current = null;
    }
  }, []);

  const startDrag = useCallback((pointerId: number, clientX: number) => {
    const block = blockRef.current;
    if (!block) return;
    const rect = block.getBoundingClientRect();
    onDragStart({ item, pointerId, clientX, itemClientLeft: rect.left, itemClientWidth: rect.width });
  }, [item, onDragStart]);

  const onPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) return;
    e.preventDefault();
    downRef.current = { ...downRef.current, x: e.clientX, y: e.clientY, pointerId: e.pointerId };
    blockRef.current?.setPointerCapture(e.pointerId);

    if (dragEnabled) {
      holdTimerRef.current = setTimeout(() => {
        startDrag(downRef.current.pointerId, downRef.current.x);
        holdTimerRef.current = null;
      }, 200);
    }
  }, [dragEnabled, startDrag]);

  const onPointerMove = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.pointerId !== downRef.current.pointerId) return;
    const dx = Math.abs(e.clientX - downRef.current.x);
    const dy = Math.abs(e.clientY - downRef.current.y);
    if (dragEnabled && (dx > 5 || dy > 5)) {
      cleanHold();
      blockRef.current?.releasePointerCapture(e.pointerId);
      startDrag(e.pointerId, e.clientX);
    }
  }, [dragEnabled, cleanHold, startDrag]);

  const onPointerUp = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    cleanHold();
    const dx = Math.abs(e.clientX - downRef.current.x);
    const dy = Math.abs(e.clientY - downRef.current.y);
    if (dx < 5 && dy < 5) {
      const now = Date.now();
      const isDouble = (now - downRef.current.lastClickTime) < 350;
      downRef.current.lastClickTime = isDouble ? 0 : now;
      if (isDouble) {
        onDblClick(item);
      } else {
        onClick(item);
      }
    }
  }, [cleanHold, item, onClick, onDblClick]);

  const onPointerEnter = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.pointerType === 'touch') return;
    const rect = blockRef.current?.getBoundingClientRect() ?? null;
    setTooltipRect(rect);
    setTooltipVisible(true);
    onHover(item, 'enter');
  }, [item, onHover]);

  const onPointerLeave = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.pointerType === 'touch') return;
    setTooltipVisible(false);
    setTooltipRect(null);
    onHover(item, 'leave');
  }, [item, onHover]);

  const onCtxMenu = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    e.preventDefault();
    onContextMenu(item, e.clientX, e.clientY);
  }, [item, onContextMenu]);

  const onKeyDown = useCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
    e.preventDefault();
    onKeyMove(item, e.key === 'ArrowLeft' ? 'left' : 'right');
  }, [item, onKeyMove]);

  const onResizePointerDown = useCallback((edge: 'left' | 'right', e: React.PointerEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    const block = blockRef.current;
    if (!block) return;
    const rect = block.getBoundingClientRect();
    onResizeStart({ item, edge, pointerId: e.pointerId, clientX: e.clientX, itemClientLeft: rect.left, itemClientWidth: rect.width });
  }, [item, onResizeStart]);

  const start = item.start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  const end = item.end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  const noDrag = readonly || !dragEnabled;

  return (
    <div className={`tl-item${isDragging ? ' dragging' : ''}`}>
      <div
        ref={blockRef}
        className={`tl-item-block${noDrag ? ' no-drag' : ''}`}
        role="button"
        tabIndex={0}
        aria-label={`${item.name}, ${start} – ${end}`}
        style={{ backgroundColor: item.color }}
        onPointerDown={readonly ? undefined : onPointerDown}
        onPointerMove={readonly ? undefined : onPointerMove}
        onPointerUp={readonly ? undefined : onPointerUp}
        onPointerEnter={readonly ? undefined : onPointerEnter}
        onPointerLeave={readonly ? undefined : onPointerLeave}
        onContextMenu={readonly ? undefined : onCtxMenu}
        onKeyDown={readonly ? undefined : onKeyDown}
      >
        {renderContent ? renderContent(item) : (
          <>
            <span className="tl-item-name">{item.name}</span>
            {showTime && <span className="tl-item-time">{start} – {end}</span>}
          </>
        )}
        {!readonly && resizable && (
          <>
            <div className="tl-handle tl-handle-left" onPointerDown={(e) => onResizePointerDown('left', e)} />
            <div className="tl-handle tl-handle-right" onPointerDown={(e) => onResizePointerDown('right', e)} />
          </>
        )}
      </div>
      {showTooltip && tooltipVisible && tooltipRect && (
        <div
          className="tl-tooltip"
          style={{ top: tooltipRect.top - 8, left: tooltipRect.left + tooltipRect.width / 2 }}
        >
          <div className="tl-tooltip-title">{item.name}</div>
          {item.description && <div className="tl-tooltip-description">{item.description}</div>}
          <div className="tl-tooltip-time">{start} – {end} · {formatDuration(item)}</div>
        </div>
      )}
    </div>
  );
}

// packages/scheduler-vue/src/TlItem.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import type { TimelineItem } from '@breeze/core';
import type { TlItemDragStartDetail, TlItemResizeStartDetail } from './types';

const props = defineProps<{
  item: TimelineItem;
  dragEnabled: boolean;
  resizable: boolean;
  showTime: boolean;
  showTooltip: boolean;
  readonly: boolean;
  isDragging: boolean;
}>();

const emit = defineEmits<{
  'drag-start': [detail: TlItemDragStartDetail];
  'resize-start': [detail: TlItemResizeStartDetail];
  'item-click': [item: TimelineItem];
  'item-dbl-click': [item: TimelineItem];
  'hover': [item: TimelineItem, type: 'enter' | 'leave'];
  'context-menu': [item: TimelineItem, x: number, y: number];
  'key-move': [item: TimelineItem, direction: 'left' | 'right'];
}>();

const blockRef = ref<HTMLDivElement | null>(null);
const tooltipVisible = ref(false);
const tooltipRect = ref<DOMRect | null>(null);

// Non-reactive mutable state — no re-render needed
const downRef = { x: 0, y: 0, pointerId: -1, lastClickTime: 0 };
let holdTimer: ReturnType<typeof setTimeout> | null = null;

watch(() => props.isDragging, (isDragging) => {
  if (isDragging) { tooltipVisible.value = false; tooltipRect.value = null; }
});

function cleanHold() {
  if (holdTimer !== null) { clearTimeout(holdTimer); holdTimer = null; }
}

function startDrag(pointerId: number, clientX: number) {
  const block = blockRef.value;
  if (!block) return;
  const rect = block.getBoundingClientRect();
  emit('drag-start', { item: props.item, pointerId, clientX, itemClientLeft: rect.left, itemClientWidth: rect.width });
}

function onPointerDown(e: PointerEvent) {
  if (props.readonly) return;
  if (e.button !== 0) return;
  e.preventDefault();
  downRef.x = e.clientX; downRef.y = e.clientY; downRef.pointerId = e.pointerId;
  blockRef.value?.setPointerCapture(e.pointerId);
  if (props.dragEnabled) {
    holdTimer = setTimeout(() => {
      startDrag(downRef.pointerId, downRef.x);
      holdTimer = null;
    }, 200);
  }
}

function onPointerMove(e: PointerEvent) {
  if (props.readonly) return;
  if (e.pointerId !== downRef.pointerId) return;
  const dx = Math.abs(e.clientX - downRef.x);
  const dy = Math.abs(e.clientY - downRef.y);
  if (props.dragEnabled && (dx > 5 || dy > 5)) {
    cleanHold();
    blockRef.value?.releasePointerCapture(e.pointerId);
    startDrag(e.pointerId, e.clientX);
  }
}

function onPointerUp(e: PointerEvent) {
  if (props.readonly) return;
  cleanHold();
  const dx = Math.abs(e.clientX - downRef.x);
  const dy = Math.abs(e.clientY - downRef.y);
  if (dx < 5 && dy < 5) {
    const now = Date.now();
    const isDouble = (now - downRef.lastClickTime) < 350;
    downRef.lastClickTime = isDouble ? 0 : now;
    if (isDouble) emit('item-dbl-click', props.item);
    else emit('item-click', props.item);
  }
}

function onPointerEnter(e: PointerEvent) {
  if (props.readonly) return;
  if (e.pointerType === 'touch') return;
  tooltipRect.value = blockRef.value?.getBoundingClientRect() ?? null;
  tooltipVisible.value = true;
  emit('hover', props.item, 'enter');
}

function onPointerLeave(e: PointerEvent) {
  if (props.readonly) return;
  if (e.pointerType === 'touch') return;
  tooltipVisible.value = false;
  tooltipRect.value = null;
  emit('hover', props.item, 'leave');
}

function onCtxMenu(e: MouseEvent) {
  if (props.readonly) return;
  e.preventDefault();
  emit('context-menu', props.item, e.clientX, e.clientY);
}

function onKeyDown(e: KeyboardEvent) {
  if (props.readonly) return;
  if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
  e.preventDefault();
  emit('key-move', props.item, e.key === 'ArrowLeft' ? 'left' : 'right');
}

function onResizePointerDown(edge: 'left' | 'right', e: PointerEvent) {
  e.preventDefault();
  e.stopPropagation();
  const block = blockRef.value;
  if (!block) return;
  const rect = block.getBoundingClientRect();
  emit('resize-start', { item: props.item, edge, pointerId: e.pointerId, clientX: e.clientX, itemClientLeft: rect.left, itemClientWidth: rect.width });
}

function formatDuration(): string {
  const ms = props.item.end.getTime() - props.item.start.getTime();
  const totalMinutes = Math.round(ms / 60_000);
  const h = Math.floor(totalMinutes / 60);
  const m = totalMinutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

const start = props.item.start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
const end = props.item.end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
</script>

<template>
  <div :class="`tl-item${isDragging ? ' dragging' : ''}`">
    <div
      ref="blockRef"
      :class="`tl-item-block${readonly || !dragEnabled ? ' no-drag' : ''}`"
      role="button"
      :tabindex="0"
      :aria-label="`${item.name}, ${start} – ${end}`"
      :style="{ backgroundColor: item.color }"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      @pointerenter="onPointerEnter"
      @pointerleave="onPointerLeave"
      @contextmenu="onCtxMenu"
      @keydown="onKeyDown"
    >
      <slot>
        <span class="tl-item-name">{{ item.name }}</span>
        <span v-if="showTime" class="tl-item-time">{{ start }} – {{ end }}</span>
      </slot>
      <template v-if="!readonly && resizable">
        <div class="tl-handle tl-handle-left" @pointerdown="(e) => onResizePointerDown('left', e)" />
        <div class="tl-handle tl-handle-right" @pointerdown="(e) => onResizePointerDown('right', e)" />
      </template>
    </div>

    <div
      v-if="showTooltip && tooltipVisible && tooltipRect"
      class="tl-tooltip"
      :style="{ top: `${tooltipRect.top - 8}px`, left: `${tooltipRect.left + tooltipRect.width / 2}px` }"
    >
      <div class="tl-tooltip-title">{{ item.name }}</div>
      <div v-if="item.description" class="tl-tooltip-description">{{ item.description }}</div>
      <div class="tl-tooltip-time">{{ start }} – {{ end }} · {{ formatDuration() }}</div>
    </div>
  </div>
</template>
