// packages/booking-react/src/MonthView.tsx
import React from 'react';
import { buildMonthGrid, parseDate } from '@widgetkit/booking';
import type { AvailabilityDay } from '@widgetkit/booking';
import { icons } from '@widgetkit/core';

const DAY_LABELS = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'];

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

interface Props {
  year: number;
  month: number; // 0-indexed
  availability: AvailabilityDay[];
  selectedDate: string | null;
  minDate?: Date;
  maxDate?: Date;
  showPrice?: boolean;
  loading?: boolean;
  onMonthChange: (year: number, month: number) => void;
  onDateSelect: (date: string) => void;
}

export function MonthView({
  year, month, availability, selectedDate, minDate, maxDate, showPrice = true,
  loading = false, onMonthChange, onDateSelect,
}: Props) {
  const weeks = buildMonthGrid(year, month);
  const dayMap = new Map(availability.map(d => [d.date, d]));

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  function prevMonth() {
    if (month === 0) onMonthChange(year - 1, 11);
    else onMonthChange(year, month - 1);
  }

  function nextMonth() {
    if (month === 11) onMonthChange(year + 1, 0);
    else onMonthChange(year, month + 1);
  }

  function isDisabled(date: string): boolean {
    const d = parseDate(date);
    if (minDate && d < minDate) return true;
    if (maxDate && d > maxDate) return true;
    const day = dayMap.get(date);
    return !day || !day.available;
  }

  return (
    <div className="bk-month">
      {loading && (
        <div className="bk-loading-overlay">
          <div className="bk-spinner" />
        </div>
      )}
      <div className="bk-month-nav">
        <button className="bk-nav-btn" onClick={prevMonth} aria-label="Previous month">
          <svg viewBox="0 0 24 24" width={16} height={16} fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d={icons.chevronLeft} /></svg>
        </button>
        <span className="bk-month-title">{MONTH_NAMES[month]} {year}</span>
        <button className="bk-nav-btn" onClick={nextMonth} aria-label="Next month">
          <svg viewBox="0 0 24 24" width={16} height={16} fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><path d={icons.chevronRight} /></svg>
        </button>
      </div>

      <div className="bk-month-grid">
        {DAY_LABELS.map(d => (
          <div key={d} className="bk-day-label">{d}</div>
        ))}

        {weeks.flat().map((date, i) => {
          if (!date) return <div key={`empty-${i}`} className="bk-day-cell bk-day-empty" />;

          const day = dayMap.get(date);
          const disabled = isDisabled(date);
          const selected = date === selectedDate;
          const dayNum = parseDate(date).getDate();
          const isToday = parseDate(date).getTime() === today.getTime();

          let cls = 'bk-day-cell';
          if (disabled) cls += ' bk-day-disabled';
          else cls += ' bk-day-available';
          if (selected) cls += ' bk-day-selected';
          if (isToday) cls += ' bk-day-today';

          return (
            <button
              key={date}
              className={cls}
              disabled={disabled}
              onClick={() => onDateSelect(date)}
              aria-label={date}
              aria-pressed={selected}
            >
              <span className="bk-day-num">{dayNum}</span>
              {showPrice && day?.price != null && (
                <span className="bk-day-price">{day.price}</span>
              )}
            </button>
          );
        })}
      </div>
    </div>
  );
}

// packages/booking-vue/src/MonthView.vue
<script setup lang="ts">
import { computed } from 'vue';
import { buildMonthGrid, parseDate } from '@widgetkit/booking';
import type { AvailabilityDay } from '@widgetkit/booking';
import { icons } from '@widgetkit/core';

const DAY_LABELS = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'];
const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const props = withDefaults(defineProps<{
  year: number;
  month: number;
  availability: AvailabilityDay[];
  selectedDate: string | null;
  minDate?: Date;
  maxDate?: Date;
  showPrice?: boolean;
  loading?: boolean;
}>(), { showPrice: true, loading: false });

const emit = defineEmits<{
  monthChange: [year: number, month: number];
  dateSelect: [date: string];
}>();

const today = new Date();
today.setHours(0, 0, 0, 0);

const weeks = computed(() => buildMonthGrid(props.year, props.month));
const dayMap = computed(() => new Map(props.availability.map(d => [d.date, d])));

function prevMonth() {
  if (props.month === 0) emit('monthChange', props.year - 1, 11);
  else emit('monthChange', props.year, props.month - 1);
}

function nextMonth() {
  if (props.month === 11) emit('monthChange', props.year + 1, 0);
  else emit('monthChange', props.year, props.month + 1);
}

function isDisabled(date: string): boolean {
  const d = parseDate(date);
  if (props.minDate && d < props.minDate) return true;
  if (props.maxDate && d > props.maxDate) return true;
  const day = dayMap.value.get(date);
  return !day || !day.available;
}

function dayClass(date: string): string {
  const disabled = isDisabled(date);
  const selected = date === props.selectedDate;
  const isToday = parseDate(date).getTime() === today.getTime();
  let cls = 'bk-day-cell';
  if (disabled) cls += ' bk-day-disabled';
  else cls += ' bk-day-available';
  if (selected) cls += ' bk-day-selected';
  if (isToday) cls += ' bk-day-today';
  return cls;
}
</script>

<template>
  <div class="bk-month">
    <div v-if="loading" class="bk-loading-overlay">
      <div class="bk-spinner" />
    </div>
    <div class="bk-month-nav">
      <button class="bk-nav-btn" @click="prevMonth" aria-label="Previous month">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path :d="icons.chevronLeft" />
        </svg>
      </button>
      <span class="bk-month-title">{{ MONTH_NAMES[month] }} {{ year }}</span>
      <button class="bk-nav-btn" @click="nextMonth" aria-label="Next month">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path :d="icons.chevronRight" />
        </svg>
      </button>
    </div>

    <div class="bk-month-grid">
      <div v-for="label in DAY_LABELS" :key="label" class="bk-day-label">{{ label }}</div>

      <template v-for="(date, i) in weeks.flat()" :key="date ?? `empty-${i}`">
        <div v-if="!date" class="bk-day-cell bk-day-empty" />
        <button
          v-else
          :class="dayClass(date)"
          :disabled="isDisabled(date)"
          :aria-label="date"
          :aria-pressed="date === selectedDate"
          @click="emit('dateSelect', date)"
        >
          <span class="bk-day-num">{{ parseDate(date).getDate() }}</span>
          <span v-if="showPrice && dayMap.get(date)?.price != null" class="bk-day-price">
            {{ dayMap.get(date)?.price }}
          </span>
        </button>
      </template>
    </div>
  </div>
</template>
