// packages/booking-vue/src/BookingScheduler.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { formatDate } from '@widgetkit/booking';
import type { AvailabilityDay, BookingMode, BookingSelection } from '@widgetkit/booking';
import MonthView from './MonthView.vue';
import DayView from './DayView.vue';

const props = withDefaults(defineProps<{
  mode?: BookingMode;
  availability: AvailabilityDay[];
  date?: Date;
  initialMonth?: Date;
  minDate?: Date;
  maxDate?: Date;
  showPrice?: boolean;
  showDuration?: boolean;
  loading?: boolean;
}>(), {
  mode: 'month-day',
  showPrice: true,
  showDuration: true,
  loading: false,
});

const emit = defineEmits<{
  select: [selection: BookingSelection];
  'month-change': [year: number, month: number];
}>();

const now = props.initialMonth ?? new Date();
const viewYear = ref(now.getFullYear());
const viewMonth = ref(now.getMonth());
const selectedDate = ref<string | null>(
  props.mode === 'day-only' && props.date ? formatDate(props.date) : null,
);
const selectedTime = ref<string | null>(null);

const dayMap = computed(() => new Map(props.availability.map(d => [d.date, d])));
const sideBySide = computed(() => props.mode === 'month-day');
const dayDate = computed(() =>
  props.mode === 'day-only' && props.date ? formatDate(props.date) : selectedDate.value,
);
const showDayView = computed(() => props.mode === 'day-only' || sideBySide.value);

function handleDateSelect(date: string) {
  selectedDate.value = date;
  selectedTime.value = null;
  if (props.mode === 'month-only') {
    emit('select', { date, duration: 0 });
  }
}

function handleTimeSelect(time: string, duration: number) {
  selectedTime.value = time;
  if (selectedDate.value) {
    emit('select', { date: selectedDate.value, time, duration });
  }
}

function handleBack() {
  selectedDate.value = null;
  selectedTime.value = null;
}

function handleMonthChange(y: number, m: number) {
  viewYear.value = y;
  viewMonth.value = m;
  emit('month-change', y, m);
}
</script>

<template>
  <div :class="['bk-root', sideBySide && 'bk-side-by-side']">
    <div class="bk-month-col">
      <MonthView
        v-if="mode === 'month-only' || mode === 'month-day'"
        :year="viewYear"
        :month="viewMonth"
        :availability="availability"
        :selected-date="selectedDate"
        :min-date="minDate"
        :max-date="maxDate"
        :show-price="showPrice"
        :loading="loading"
        @month-change="handleMonthChange"
        @date-select="handleDateSelect"
      />
    </div>

    <DayView
      v-if="showDayView && dayDate"
      :date="dayDate"
      :day="dayMap.get(dayDate)"
      :selected-time="selectedTime"
      :show-back="mode === 'month-day'"
      :show-price="showPrice"
      :show-duration="showDuration"
      :loading="loading"
      @time-select="handleTimeSelect"
      @back="handleBack"
    />
  </div>
</template>

// packages/booking-react/src/BookingScheduler.tsx
import React, { useState } from 'react';
import { formatDate } from '@widgetkit/booking';
import type { AvailabilityDay, BookingMode, BookingSelection } from '@widgetkit/booking';
import { MonthView } from './MonthView';
import { DayView } from './DayView';

export interface BookingSchedulerProps {
  mode?: BookingMode;
  availability: AvailabilityDay[];

  // For day-only mode: which day to display
  date?: Date;

  // Month view start
  initialMonth?: Date;
  minDate?: Date;
  maxDate?: Date;

  // Display
  showPrice?: boolean;
  showDuration?: boolean;
  loading?: boolean;

  onSelect?: (selection: BookingSelection) => void;
  onMonthChange?: (year: number, month: number) => void;
}

export function BookingScheduler({
  mode = 'month-day',
  availability,
  date: dateProp,
  initialMonth,
  minDate,
  maxDate,
  showPrice = true,
  showDuration = true,
  loading = false,
  onSelect,
  onMonthChange,
}: BookingSchedulerProps) {
  const now = initialMonth ?? new Date();

  const [viewYear, setViewYear] = useState(now.getFullYear());
  const [viewMonth, setViewMonth] = useState(now.getMonth());
  const [selectedDate, setSelectedDate] = useState<string | null>(
    mode === 'day-only' && dateProp ? formatDate(dateProp) : null,
  );
  const [selectedTime, setSelectedTime] = useState<string | null>(null);

  const dayMap = new Map(availability.map(d => [d.date, d]));

  function handleDateSelect(date: string) {
    setSelectedDate(date);
    setSelectedTime(null);
    if (mode === 'month-only') {
      onSelect?.({ date, duration: 0 });
    }
  }

  function handleTimeSelect(time: string, duration: number) {
    setSelectedTime(time);
    if (selectedDate) {
      onSelect?.({ date: selectedDate, time, duration });
    }
  }

  function handleBack() {
    setSelectedDate(null);
    setSelectedTime(null);
  }

  const sideBySide = mode === 'month-day';
  const showDayView = mode === 'day-only' || sideBySide;
  const dayDate = mode === 'day-only' && dateProp ? formatDate(dateProp) : selectedDate;

  return (
    <div className={`bk-root${sideBySide ? ' bk-side-by-side' : ''}`}>
      <div className="bk-month-col">
        {(mode === 'month-only' || mode === 'month-day') && (
          <MonthView
            year={viewYear}
            month={viewMonth}
            availability={availability}
            selectedDate={selectedDate}
            minDate={minDate}
            maxDate={maxDate}
            showPrice={showPrice}
            loading={loading}
            onMonthChange={(y, m) => { setViewYear(y); setViewMonth(m); onMonthChange?.(y, m); }}
            onDateSelect={handleDateSelect}
          />
        )}
      </div>

      {showDayView && dayDate && (
        <DayView
          date={dayDate}
          day={dayMap.get(dayDate)}
          selectedTime={selectedTime}
          showPrice={showPrice}
          showDuration={showDuration}
          loading={loading}
          onTimeSelect={handleTimeSelect}
          onBack={mode === 'month-day' ? handleBack : undefined}
        />
      )}
    </div>
  );
}
